version: '3'

services:
  mongo-test:
    image: mongo:4.0.3
    container_name: mongo-test
    ports:
      - 27017:27017
    volumes:
      - ./data/test:/data/db
  node-app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "4000:4000"
    env_file:
      - .env.test
    volumes:
      - './:/app/'
      - '/app/cron/'
    depends_on:
      - mongo-test
    
    