version: '3'

services:
  mongo-dev:
    image: mongo:4.0.3
    container_name: mongo-dev
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  node-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - .env.dev
    volumes:
      - ./:/app/
    depends_on:
      - mongo-dev
    
    