version: '3'

services:
  mongo-test:
    image: mongo:4.0.3
    container_name: mongo-test
    env_file:
      - .env.test
  node-app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: node-app-test
    env_file:
      - .env.test
    depends_on:
      - mongo-test
    
    