import { Product } from '../interfaces';

export const initialValues: Product[] = [
  {
    code: 17,
    status: 'published',
    url: 'http://world-en.openfoodfacts.org/product/0000000000017/vitoria-crackers',
    creator: 'kiliweb',
    created_t: 1529059080,
    last_modified_t: 1561463718,
    product_name: 'Vitória crackers',
    quantity: '',
    brands: '',
    categories: '',
    labels: '',
    cities: '',
    purchase_places: '',
    stores: '',
    ingredients_text: '',
    traces: '',
    serving_size: '',
    serving_quantity: 0,
    nutriscore_score: 0,
    nutriscore_grade: '',
    main_category: '',
    image_url:
      'https://static.openfoodfacts.org/images/products/000/000/000/0017/front_fr.4.400.jpg',
    imported_t: new Date('2022-10-31T21:29:21.516Z'),
  },
  {
    code: 31,
    status: 'published',
    url: 'http://world-en.openfoodfacts.org/product/0000000000031/cacao',
    creator: 'isagoofy',
    created_t: 1539464774,
    last_modified_t: 1539464817,
    product_name: 'Cacao',
    quantity: '130 g',
    brands: '',
    categories: '',
    labels: '',
    cities: '',
    purchase_places: '',
    stores: '',
    ingredients_text: '',
    traces: '',
    serving_size: '',
    serving_quantity: 0,
    nutriscore_score: 0,
    nutriscore_grade: '',
    main_category: '',
    image_url:
      'https://static.openfoodfacts.org/images/products/000/000/000/0031/front_fr.3.400.jpg',
    imported_t: new Date('2022-10-31T21:29:58.572Z'),
  },
  {
    code: 123,
    status: 'published',
    url: 'http://world-en.openfoodfacts.org/product/0000000000123/sauce-sweety-chili-0',
    creator: 'kiliweb',
    created_t: 1535737982,
    last_modified_t: 1535737986,
    product_name: 'Sauce Sweety chili 0%',
    quantity: '',
    brands: '',
    categories: '',
    labels: '',
    cities: '',
    purchase_places: '',
    stores: '',
    ingredients_text: '',
    traces: '',
    serving_size: '',
    serving_quantity: 0,
    nutriscore_score: 0,
    nutriscore_grade: '',
    main_category: '',
    image_url:
      'https://static.openfoodfacts.org/images/products/000/000/000/0123/front_fr.4.400.jpg',
    imported_t: new Date('2022-10-31T21:29:58.574Z'),
  },
  {
    code: 178,
    status: 'published',
    url: 'http://world-en.openfoodfacts.org/product/0000000000178/mini-coco',
    creator: 'kiliweb',
    created_t: 1542456332,
    last_modified_t: 1542456333,
    product_name: 'Mini coco',
    quantity: '',
    brands: '',
    categories: '',
    labels: '',
    cities: '',
    purchase_places: '',
    stores: '',
    ingredients_text: '',
    traces: '',
    serving_size: '',
    serving_quantity: 0,
    nutriscore_score: 0,
    nutriscore_grade: '',
    main_category: '',
    image_url:
      'https://static.openfoodfacts.org/images/products/000/000/000/0178/front_fr.4.400.jpg',
    imported_t: new Date('2022-10-31T21:29:58.575Z'),
  },
  {
    code: 208,
    status: 'published',
    url: 'http://world-en.openfoodfacts.org/product/0000000000208/pistou-d-ail-des-ours',
    creator: 'kiliweb',
    created_t: 1544207680,
    last_modified_t: 1544207683,
    product_name: "Pistou d'ail des ours",
    quantity: '',
    brands: '',
    categories: '',
    labels: '',
    cities: '',
    purchase_places: '',
    stores: '',
    ingredients_text: '',
    traces: '',
    serving_size: '',
    serving_quantity: 0,
    nutriscore_score: 0,
    nutriscore_grade: '',
    main_category: '',
    image_url:
      'https://static.openfoodfacts.org/images/products/000/000/000/0208/front_fr.4.400.jpg',
    imported_t: new Date('2022-10-31T21:29:58.576Z'),
  },
  {
    code: 284,
    status: 'published',
    url: 'http://world-en.openfoodfacts.org/product/0000000000284/pain-mais',
    creator: 'kiliweb',
    created_t: 1547120245,
    last_modified_t: 1563551052,
    product_name: 'Pain maïs',
    quantity: '',
    brands: '',
    categories: '',
    labels: '',
    cities: '',
    purchase_places: '',
    stores: '',
    ingredients_text: '',
    traces: '',
    serving_size: '',
    serving_quantity: 0,
    nutriscore_score: 0,
    nutriscore_grade: '',
    main_category: '',
    image_url:
      'https://static.openfoodfacts.org/images/products/000/000/000/0284/front_fr.4.400.jpg',
    imported_t: new Date('2022-10-31T21:29:58.576Z'),
  },
  {
    code: 291,
    status: 'published',
    url: 'http://world-en.openfoodfacts.org/product/0000000000291/mendiants',
    creator: 'kiliweb',
    created_t: 1534239669,
    last_modified_t: 1534239732,
    product_name: 'Mendiants',
    quantity: '',
    brands: '',
    categories: '',
    labels: '',
    cities: '',
    purchase_places: '',
    stores: '',
    ingredients_text: '',
    traces: '',
    serving_size: '',
    serving_quantity: 0,
    nutriscore_score: 0,
    nutriscore_grade: '',
    main_category: '',
    image_url:
      'https://static.openfoodfacts.org/images/products/000/000/000/0291/front_fr.4.400.jpg',
    imported_t: new Date('2022-10-31T21:29:58.577Z'),
  },
  {
    code: 54,
    status: 'published',
    url: 'http://world-en.openfoodfacts.org/product/000000000054/limonade-artisanale-a-la-rose',
    creator: 'kiliweb',
    created_t: 1582569031,
    last_modified_t: 1582569032,
    product_name: 'Limonade artisanale a la rose',
    quantity: '',
    brands: '',
    categories: '',
    labels: '',
    cities: '',
    purchase_places: '',
    stores: '',
    ingredients_text: '',
    traces: '',
    serving_size: '',
    serving_quantity: 0,
    nutriscore_score: 0,
    nutriscore_grade: '',
    main_category: '',
    image_url:
      'https://static.openfoodfacts.org/images/products/000/000/000/054/front_fr.3.400.jpg',
    imported_t: new Date('2022-10-31T21:29:58.579Z'),
  },
  {
    code: 75,
    status: 'published',
    url: 'http://world-en.openfoodfacts.org/product/000000000075/sachet-calisson',
    creator: 'kiliweb',
    created_t: 1577358367,
    last_modified_t: 1577358368,
    product_name: 'Sachet calisson',
    quantity: '',
    brands: '',
    categories: '',
    labels: '',
    cities: '',
    purchase_places: '',
    stores: '',
    ingredients_text: '',
    traces: '',
    serving_size: '',
    serving_quantity: 0,
    nutriscore_score: 0,
    nutriscore_grade: '',
    main_category: '',
    image_url:
      'https://static.openfoodfacts.org/images/products/000/000/000/075/front_fr.3.400.jpg',
    imported_t: new Date('2022-10-31T21:29:58.581Z'),
  },
  {
    code: 80,
    status: 'published',
    url: 'http://world-en.openfoodfacts.org/product/000000000080/pur-jus-de-pomme',
    creator: 'kiliweb',
    created_t: 1612447663,
    last_modified_t: 1612447667,
    product_name: 'Pur jus de pomme',
    quantity: '',
    brands: '',
    categories: '',
    labels: '',
    cities: '',
    purchase_places: '',
    stores: '',
    ingredients_text: '',
    traces: '',
    serving_size: '',
    serving_quantity: 0,
    nutriscore_score: 0,
    nutriscore_grade: '',
    main_category: '',
    image_url:
      'https://static.openfoodfacts.org/images/products/000/000/000/080/front_fr.3.400.jpg',
    imported_t: new Date('2022-10-31T21:29:58.581Z'),
  },
  {
    code: 88,
    status: 'published',
    url: 'http://world-en.openfoodfacts.org/product/000000000088/pate-d-amende',
    creator: 'kiliweb',
    created_t: 1577358222,
    last_modified_t: 1577358410,
    product_name: "Pate d'amende",
    quantity: '',
    brands: '',
    categories: "Pâte d'amende",
    labels: '',
    cities: '',
    purchase_places: '',
    stores: '',
    ingredients_text: '',
    traces: '',
    serving_size: '',
    serving_quantity: 0,
    nutriscore_score: 0,
    nutriscore_grade: '',
    main_category: 'fr:pate-d-amende',
    image_url:
      'https://static.openfoodfacts.org/images/products/000/000/000/088/front_fr.3.400.jpg',
    imported_t: new Date('2022-10-31T21:29:58.582Z'),
  },
  {
    code: 949,
    status: 'published',
    url: 'http://world-en.openfoodfacts.org/product/0000000000949/salade-de-carottes-rapees',
    creator: 'kiliweb',
    created_t: 1523440813,
    last_modified_t: 1565268412,
    product_name: 'Salade de carottes râpées',
    quantity: '',
    brands: '',
    categories:
      'Plats préparés, Légumes préparés, Carottes râpées, Carottes râpées assaisonnées',
    labels: '',
    cities: '',
    purchase_places: '',
    stores: '',
    ingredients_text: '',
    traces: '',
    serving_size: '',
    serving_quantity: 0,
    nutriscore_score: 1,
    nutriscore_grade: 'b',
    main_category: 'en:seasoned-shredded-carrots',
    image_url:
      'https://static.openfoodfacts.org/images/products/000/000/000/0949/front_fr.4.400.jpg',
    imported_t: new Date('2022-10-31T21:29:58.610Z'),
  },
  {
    code: 970,
    status: 'published',
    url: 'http://world-en.openfoodfacts.org/product/0000000000970/fromage-blanc-aux-myrtilles',
    creator: 'kiliweb',
    created_t: 1520506368,
    last_modified_t: 1561463726,
    product_name: 'Fromage blanc aux myrtilles',
    quantity: '',
    brands: '',
    categories: '',
    labels: '',
    cities: '',
    purchase_places: '',
    stores: '',
    ingredients_text: '',
    traces: '',
    serving_size: '',
    serving_quantity: 0,
    nutriscore_score: 0,
    nutriscore_grade: '',
    main_category: '',
    image_url:
      'https://static.openfoodfacts.org/images/products/000/000/000/0970/front_fr.4.400.jpg',
    imported_t: new Date('2022-10-31T21:29:58.611Z'),
  },
  {
    code: 1001,
    status: 'published',
    url: 'http://world-en.openfoodfacts.org/product/0000000001001',
    creator: 'openfoodfacts-contributors',
    created_t: 1537766416,
    last_modified_t: 1537766416,
    product_name: '',
    quantity: '',
    brands: '',
    categories: '',
    labels: '',
    cities: '',
    purchase_places: '',
    stores: '',
    ingredients_text: '',
    traces: '',
    serving_size: '',
    serving_quantity: 0,
    nutriscore_score: 0,
    nutriscore_grade: '',
    main_category: '',
    image_url: '',
    imported_t: new Date('2022-10-31T21:29:58.611Z'),
  },
  {
    code: 1007,
    status: 'published',
    url: 'http://world-en.openfoodfacts.org/product/0000000001007/vainilla',
    creator: 'kiliweb',
    created_t: 1538127563,
    last_modified_t: 1538127565,
    product_name: 'Vainilla',
    quantity: '',
    brands: '',
    categories: '',
    labels: '',
    cities: '',
    purchase_places: '',
    stores: '',
    ingredients_text: '',
    traces: '',
    serving_size: '',
    serving_quantity: 0,
    nutriscore_score: 0,
    nutriscore_grade: '',
    main_category: '',
    image_url:
      'https://static.openfoodfacts.org/images/products/000/000/000/1007/front_fr.4.400.jpg',
    imported_t: new Date('2022-10-31T21:29:58.612Z'),
  },
  {
    code: 112,
    status: 'published',
    url: 'http://world-en.openfoodfacts.org/product/000000000112/iogurt-de-cabra',
    creator: 'kiliweb',
    created_t: 1613071207,
    last_modified_t: 1613071209,
    product_name: 'Iogurt de cabra',
    quantity: '',
    brands: '',
    categories: '',
    labels: '',
    cities: '',
    purchase_places: '',
    stores: '',
    ingredients_text: '',
    traces: '',
    serving_size: '',
    serving_quantity: 0,
    nutriscore_score: 0,
    nutriscore_grade: '',
    main_category: '',
    image_url:
      'https://static.openfoodfacts.org/images/products/000/000/000/112/front_es.3.400.jpg',
    imported_t: new Date('2022-10-31T21:29:58.612Z'),
  },
  {
    code: 1137,
    status: 'published',
    url: 'http://world-en.openfoodfacts.org/product/0000000001137/baguette-parisien',
    creator: 'kiliweb',
    created_t: 1539781575,
    last_modified_t: 1539781578,
    product_name: 'Baguette parisien',
    quantity: '',
    brands: '',
    categories: '',
    labels: '',
    cities: '',
    purchase_places: '',
    stores: '',
    ingredients_text: '',
    traces: '',
    serving_size: '',
    serving_quantity: 0,
    nutriscore_score: 0,
    nutriscore_grade: '',
    main_category: '',
    image_url:
      'https://static.openfoodfacts.org/images/products/000/000/000/1137/front_fr.4.400.jpg',
    imported_t: new Date('2022-10-31T21:29:58.613Z'),
  },
  {
    code: 114,
    status: 'published',
    url: 'http://world-en.openfoodfacts.org/product/000000000114/chocolate-n-3-jeff-de-bruges',
    creator: 'kiliweb',
    created_t: 1580066482,
    last_modified_t: 1609945229,
    product_name: 'Chocolate n 3',
    quantity: '80 g',
    brands: 'Jeff de Bruges',
    categories: '',
    labels: 'en:made-in-france',
    cities: '',
    purchase_places: '',
    stores: '',
    ingredients_text: '',
    traces: '',
    serving_size: '',
    serving_quantity: 0,
    nutriscore_score: 0,
    nutriscore_grade: '',
    main_category: '',
    image_url:
      'https://static.openfoodfacts.org/images/products/000/000/000/114/front_fr.3.400.jpg',
    imported_t: new Date('2022-10-31T21:29:58.614Z'),
  },
  {
    code: 1151,
    status: 'published',
    url: 'http://world-en.openfoodfacts.org/product/0000000001151/baguette-lyonnais',
    creator: 'kiliweb',
    created_t: 1537883404,
    last_modified_t: 1537883538,
    product_name: '&quot";Baguette Lyonnais&quot;"',
    quantity: '',
    brands: '',
    categories: '',
    labels: '',
    cities: '',
    purchase_places: '',
    stores: '',
    ingredients_text: '',
    traces: '',
    serving_size: '',
    serving_quantity: 0,
    nutriscore_score: 0,
    nutriscore_grade: '',
    main_category: '',
    image_url:
      'https://static.openfoodfacts.org/images/products/000/000/000/1151/front_fr.4.400.jpg',
    imported_t: new Date('2022-10-31T21:29:58.614Z'),
  },
];
